import React from "react";
import { useEffect, useState } from "react";
import { fetchDaftar } from "../../components/apiData";
import { Container, Row, Col, Card, Button, Pagination } from "react-bootstrap";
import Navbar from "../../components/navbar/navbar";
import { useRouter } from "next/router";
import Head from "next/head";

export default function daftarKomik() {
  const router = useRouter();
  const { page } = router.query;
  const [komikPage, setPage] = useState([]);

  async function setDaftar(page) {
    const res = await fetchDaftar(page);
    setPage(res.mangas);
  }

  function ImageOnError(e) {
    e.target.onerror = null;
    const base64img = btoa(e.target.src);

    return (e.target.src = `https://bypass.katowproject.my.id/?q=${base64img}`);
  }

  useEffect(() => {
    if (!router.isReady) return;
    console.log(page);
    setDaftar(page);
  }, [router.isReady]);

  return (
    <div>
      <Head>
        <title>Ryukomik | Tempat baca manga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mb-3">
        <h2 style={{ fontFamily: "Poppins" }} className="container mt-5">
          Daftar Komik
        </h2>
      </div>
      <Container>
        <hr />
        <Row className="g-4">
          {komikPage.map((pageitems) => (
            <Col className="col-lg-3 d-flex align-items-stretch">
              <Card>
                <Card.Img
                  variant="top"
                  src={pageitems.thumb}
                  onError={ImageOnError}
                />
                <Card.Body>
                  <Card.Title>{pageitems.name}</Card.Title>
                  <Card.Text>Baca {pageitems.name}</Card.Text>
                  <Button variant="danger">Baca sekarang!</Button>
                </Card.Body>
              </Card>
            </Col>
          ))}
        </Row>
        <Pagination>
          <Pagination.First />
          <Pagination.Prev />
          <Pagination.Item>{1}</Pagination.Item>
          <Pagination.Ellipsis />

          <Pagination.Item>{10}</Pagination.Item>
          <Pagination.Item>{11}</Pagination.Item>
          <Pagination.Item active>{12}</Pagination.Item>
          <Pagination.Item>{13}</Pagination.Item>
          <Pagination.Item disabled>{14}</Pagination.Item>

          <Pagination.Ellipsis />
          <Pagination.Item>{20}</Pagination.Item>
          <Pagination.Next />
          <Pagination.Last />
        </Pagination>
        <hr />
      </Container>
    </div>
  );
}
