import React from "react";
import { useEffect, useState } from "react";
import { Container, Row, Col, Card, Button, Pagination } from "react-bootstrap";
import Navbar from "../../../components/navbar/navbar";
import { useRouter } from "next/router";
import Head from "next/head";

export default function Manhwa() {
  const router = useRouter();
  const { manhwa: page } = router.query;
  const [manhwaPage, setPage] = useState([]);
  const [buttonPage, setButton] = useState([]);

  async function setDaftar(page = 1) {
    const res = await fetch(
      "https://komi.katowproject.app/api/komikindo/komikk/manhwa/page/" + page
    );
    const data = await res.json();
    setPage(data.mangas);
    const pagination = paginationHandling(data.pagination);
    setButton(pagination);
  }

  function paginationHandling(pagination) {
    const arr = [];
    for (const p of pagination) {
      if (!p.url || !p.endpoint) {
        arr.push(
          <Pagination.Item
            key={p.name}
            style={{ fontFamily: "Poppins" }}
            active
          >
            {p.name}
          </Pagination.Item>
        );
      } else {
        let path = p.endpoint?.split("/")[2];
        if (!path) path = "1";
        arr.push(
          <Pagination.Item
            key={p.name}
            href={`/komikk/manhwa/page/${path}`}
            as={`/komikk/manhwa/page/${path}`}
            style={{ fontFamily: "Poppins" }}
          >
            {p.name}
          </Pagination.Item>
        );
      }
    }

    return arr;
  }

  function ImageOnError(e) {
    e.target.onerror = null;
    const base64img = btoa(e.target.src);

    return (e.target.src = `https://bypass.katowproject.my.id/?q=${base64img}`);
  }

  useEffect(() => {
    if (!router.isReady) return;
    setDaftar(page);
  }, [router.isReady]);

  return (
    <div>
      <Head>
        <title>Ryukomik | Tempat baca manga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mb-3">
        <h2 style={{ fontFamily: "Poppins" }} className="container mt-5">
          Daftar Komik
        </h2>
      </div>
      <Container>
        <hr />
        <Row className="g-4">
          {manhwaPage.map((pageitems) => (
            <Col className="col-lg-3 d-flex align-items-stretch">
              <Card>
                <Card.Img
                  variant="top"
                  src={pageitems.thumb}
                  onError={ImageOnError}
                />
                <Card.Body>
                  <Card.Title style={{ fontFamily: "Poppins" }}>
                    {pageitems.name}
                  </Card.Title>
                  <Card.Text style={{ fontFamily: "Poppins" }}>
                    Baca {pageitems.name}
                  </Card.Text>
                  <Button
                    variant="danger"
                    href={`/${pageitems.link.endpoint}`}
                    style={{ fontFamily: "Poppins" }}
                  >
                    Baca sekarang!
                  </Button>
                </Card.Body>
              </Card>
            </Col>
          ))}
          <Pagination className="justify-content-center" size="lg">
            {buttonPage}
          </Pagination>
        </Row>
        <hr />
      </Container>
    </div>
  );
}
