import React from "react";
import { useEffect, useState } from "react";
import { fetchDetail } from "../../components/apiData";
import DB from "../../helper/localstorage";
import {
  Container,
  Col,
  Row,
  Image,
  ListGroup,
  Table,
  Button,
} from "react-bootstrap";
import Navbar from "../components/navbar/navbar";
import Head from "next/head";
import { useRouter } from "next/router";
import { AiOutlinePlusCircle, AiOutlineMinusCircle } from "react-icons/ai";

export default function Komik() {
  const db = new DB();
  const router = useRouter();
  const { komik } = router.query;
  const [komikDetail, setDetail] = useState([]);
  const [komikGenre, setGenreKomik] = useState([]);
  const [komikChapter, setChapter] = useState([]);
  const [bookmark, setBookmark] = useState([]);

  async function funDetail() {
    const res = await fetchDetail(komik);
    setDetail(res);
    setGenreKomik(res.genres);
    setChapter(res.chapters);
  }

  //Funtion Ngecek bookmark udah ada di bookmark atau belum
  async function bookmarkCheck() {
    const bookmarks = db.get(komik);
    setBookmark(bookmarks);
  }

  //Function Buat nambahin ke bookmark
  async function setToBookmark() {
    const endpoint = komik;
    const res = await fetch(
      `https://komi.katowproject.app/api/komikindo/komik/${endpoint}`
    );
    const json = await res.json();
    db.set(json);

    // update button
    bookmarkCheck(komik);
  }

  //Function HapusBookmark
  async function deleteBookmark() {
    db.remove(komik);
    // update button
    bookmarkCheck(komik);
  }
  function ImageOnError(e) {
    e.target.onerror = null;
    const base64img = btoa(e.target.src);

    return (e.target.src = `https://bypass.katowproject.my.id/?q=${base64img}`);
  }

  useEffect(() => {
    if (!router.isReady) return;
    funDetail(komik);
    bookmarkCheck(komik);
  }, [router.isReady]);
  return (
    <div>
      <Head>
        <title>Ryukomik | Tempat baca manga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Container className="mt-5 mb-5">
          <h1 style={{ fontFamily: "Poppins", fontWeight: "bold" }}>
            {komikDetail.title}
          </h1>
          <Row gy={2} className="mb-5">
            <Col md={4} className="mt-5">
              <Image
                src={komikDetail.thumb}
                width={407}
                height={578}
                className="rounded img-fluid"
                onError={ImageOnError}
              />
              {!bookmark ? (
                <Button
                  variant="danger"
                  className="mt-2 d-flex mx-auto justify-content-center"
                  size="lg"
                  onClick={setToBookmark}
                >
                  <AiOutlinePlusCircle /> Bookmark
                </Button>
              ) : (
                <Button
                  variant="danger"
                  className="mt-2 d-flex mx-auto justify-content-center"
                  size="lg"
                  onClick={deleteBookmark}
                >
                  <AiOutlineMinusCircle /> Unbookmark
                </Button>
              )}
              {/* <Button
                variant="danger"
                className="mt-2 d-flex mx-auto justify-content-center"
                size="lg"
                onClick={setToBookmark}
              >
                Bookmark
              </Button> */}
            </Col>
            <Col md={6} className="mt-5">
              <ListGroup>
                <ListGroup.Item>
                  <span style={{ fontFamily: "Poppins", fontWeight: "bold" }}>
                    Alternatif :
                  </span>
                  {komikDetail.alter}
                </ListGroup.Item>
                <ListGroup.Item>
                  <span style={{ fontFamily: "Poppins", fontWeight: "bold" }}>
                    Status :
                  </span>
                  {komikDetail.status}
                </ListGroup.Item>
                <ListGroup.Item>
                  <span style={{ fontFamily: "Poppins", fontWeight: "bold" }}>
                    Author :
                  </span>
                  {komikDetail.author}
                </ListGroup.Item>
                <ListGroup.Item>
                  <span style={{ fontFamily: "Poppins", fontWeight: "bold" }}>
                    Illustator :
                  </span>
                  {komikDetail.illustator}
                </ListGroup.Item>
                <ListGroup.Item>
                  <span style={{ fontFamily: "Poppins", fontWeight: "bold" }}>
                    Genre :
                  </span>
                  {komikGenre.map((genreitems) => (
                    <> {genreitems.name},</>
                  ))}
                </ListGroup.Item>
                <ListGroup.Item>
                  <span style={{ fontFamily: "Poppins", fontWeight: "bold" }}>
                    Score : ⭐
                  </span>
                  {komikDetail.score}
                </ListGroup.Item>
              </ListGroup>
            </Col>
          </Row>
          <hr />
          <h2
            style={{ fontFamily: "Poppins", fontWeight: "bold" }}
            className="mt-5"
          >
            Chapter List
          </h2>
          <div
            className="mt-5"
            style={{
              overflow: "auto",
              height: "500px",
              position: "relative",
              display: "block",
            }}
          >
            <Table className="table mb-0">
              {komikChapter.map((chapterlist) => (
                <tbody>
                  <tr>
                    <td style={{ fontFamily: "Poppins", fontWeight: "bold" }}>
                      {chapterlist.name}
                    </td>
                    <td className="justify-content-end d-flex">
                      <Button
                        variant="danger"
                        href={`/chapter/${chapterlist.link.endpoint.split("https://komikindo.one")[1]}`}
                        style={{ fontFamily: "Poppins" }}
                      >
                        Baca Komik
                      </Button>
                    </td>
                  </tr>
                </tbody>
              ))}
            </Table>
          </div>
        </Container>
      </main>
    </div>
  );
}
