import React from "react";
import { useEffect, useState } from "react";
import { fetchBaca } from "../../components/apiData";
import { Container, Image, Pagination } from "react-bootstrap";
import Navbar from "../components/navbar/navbar";
import { useRouter } from "next/router";
import { FaArrowUp } from "react-icons/fa";
import Head from "next/head";
export default function Chapter() {
  const router = useRouter();
  const { chapter } = router.query;
  const [chapterList, setChapter] = useState([]);
  const [chapterImage, setChapterImage] = useState([]);
  const [chapterLink, setChapterLink] = useState([]);

  const top = () => {
    window.scrollTo(0, 0);
  };

  /*function chapterPage(data) {
    if (!data.prev) {
      return (
        <Pagination.Item style={{ fontFamily: "Poppins" }} disabled>
          {"<<"} Sebelumnya
        </Pagination.Item>
      );
    } else {
      return (
        <Pagination.Item style={{ fontFamily: "Poppins" }} href={data.prev}>
          {"<<"} Sebelumnya
        </Pagination.Item>
      );
    }
  }*/

  async function setChapterDetail() {
    const res = await fetchBaca(chapter);
    setChapter(res);
    setChapterImage(res.images);
    setChapterLink(res.chapter);
    console.log(res);
  }

  function ImageOnError(e) {
    e.target.onerror = null;
    const base64img = btoa(e.target.src);

    return (e.target.src = `https://bypass.katowproject.my.id/?q=${base64img}`);
  }

  useEffect(() => {
    if (!router.isReady) return;
    setChapterDetail(chapter);
  }, [router.isReady]);

  return (
    <div>
      <Head>
        <title>Ryukomik | Tempat baca manga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Container className="mt-5 mb-5">
          <h1 style={{ fontFamily: "Poppins", fontWeight: "bold" }}>
            {chapterList.title}
          </h1>
          <Pagination className="d-flex justify-content-center mt-5" size="md">
            {chapterLink.prev ? (
              <Pagination.Item
                style={{ fontFamily: "Poppins" }}
                href={`/chapter/${chapterLink.prev.split("https://komikindo.one")[1]}`}
              >
                {"<<"} Sebelumnya
              </Pagination.Item>
            ) : (
              <Pagination.Item style={{ fontFamily: "Poppins" }} disabled>
                {"<<"} Sebelumnya
              </Pagination.Item>
            )}

            {chapterLink.next ? (
              <Pagination.Item
                style={{ fontFamily: "Poppins" }}
                href={`/chapter/${chapterLink.next.split("https://komikindo.one")[1]}`}
              >
                Selanjutnya {">>"}
              </Pagination.Item>
            ) : (
              <Pagination.Item style={{ fontFamily: "Poppins" }} disabled>
                Selanjutnya {">>"}
              </Pagination.Item>
            )}
          </Pagination>
          <hr />
          {chapterImage.map((gambaritems) => (
            <div className="d-flex justify-content-center">
              <Image
                className="img-fluid"
                src={gambaritems}
                onError={ImageOnError}
              ></Image>
            </div>
          ))}
          <hr />
          <Pagination className="d-flex justify-content-center mt-5" size="md">
            {/* <Pagination.Item
              style={{ fontFamily: "Poppins" }}
              href={chapterLink.prev}
            >
              {"<<"} Sebelumnya
            </Pagination.Item>
            <Pagination.Item
              style={{ fontFamily: "Poppins" }}
              href={chapterLink.next}
            >
              Selanjutnya {">>"}
            </Pagination.Item> */}

            {chapterLink.prev ? (
              <Pagination.Item
                style={{ fontFamily: "Poppins" }}
                href={chapterLink.prev}
              >
                {"<<"} Sebelumnya
              </Pagination.Item>
            ) : (
              <Pagination.Item style={{ fontFamily: "Poppins" }} disabled>
                {"<<"} Sebelumnya
              </Pagination.Item>
            )}

            {chapterLink.next ? (
              <Pagination.Item
                style={{ fontFamily: "Poppins" }}
                href={chapterLink.next}
              >
                Selanjutnya {">>"}
              </Pagination.Item>
            ) : (
              <Pagination.Item style={{ fontFamily: "Poppins" }} disabled>
                Selanjutnya {">>"}
              </Pagination.Item>
            )}
          </Pagination>
        </Container>
      </main>
      <button
        onClick={top}
        style={{
          background: "red",
          position: "fixed",
          bottom: "16px",
          right: "32px",
          width: "50px",
          height: "50px",
          borderRadius: "50%",
          border: "none",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontSize: "32px",
          color: "white",
          textDecoration: "none",
        }}
      >
        <FaArrowUp />
      </button>
    </div>
  );
}
