import React from "react";
import DB from "../../helper/localstorage";
import Navbar from "../components/navbar/navbar";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Container, Row, Col, Card, Button, Image } from "react-bootstrap";

export default function Index() {
  const db = new DB();
  const [bookmark, setBookmark] = useState([]);

  async function getBookmark() {
    const bookmarks = db.get_all();
    setBookmark(bookmarks);
  }

  //Function Menampilkan isi bookmark
  function bookmarkHandling() {
    const arr = [];
    for (const b of bookmark) {
      //b.url = b.url?.split("/");
      arr.push(b);
    }
    if (arr.length < 1)
      return (
        <>
          <div>
            <h1>Bookmark kosong</h1>
            <Image
              className="img-fluid d-flex"
              src="ryuko_notfound.png"
            ></Image>
          </div>
        </>
      );

    return arr.map((bookmark) => (
      <Col className="col-lg-3 d-flex align-items-stretch">
        <Card>
          <Card.Img variant="top" src={bookmark.thumb} onError={ImageOnError} />
          <Card.Body>
            <Card.Title style={{ fontFamily: "Poppins" }}>
              {bookmark.name}
            </Card.Title>
            <Card.Text style={{ fontFamily: "Poppins" }}>
              Baca {bookmark.title}
            </Card.Text>
            <Button
              variant="danger"
              href={`/komik/${bookmark.url?.split("/")[6]}`}
              style={{ fontFamily: "Poppins" }}
            >
              Baca sekarang!
            </Button>
          </Card.Body>
        </Card>
      </Col>
    ));
  }

  function ImageOnError(e) {
    e.target.onerror = null;
    const base64img = btoa(e.target.src);

    return (e.target.src = `https://bypass.katowproject.my.id/?q=${base64img}`);
  }

  useEffect(() => {
    getBookmark();
  }, []);

  return (
    <div>
      <Head>
        <title>Ryukomik | Tempat baca manga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className="mb-3">
          <h2 style={{ fontFamily: "Poppins" }} className="container mt-5">
            Bookmark Komik
          </h2>
        </div>
        <Container>
          <hr />
          <Row className="g-4">{bookmarkHandling()}</Row>
        </Container>
      </main>
    </div>
  );
}
